<template>
  <v-layout fluid justify-center align-start align="start" column class="HomeView content-page" :class="{ 'isMobile': isMobile }">
    <v-flex sm12 class="the-layout">
      <center>
        <h1 class="coolfont">PETER DAVID HIRSCHBERG</h1>
        <p>
          <span class="bullet">Web Developer</span>
          <span class="bullet">C++ Developer</span>
          <span class="bullet">Artist</span>
          <span class="bullet">3D Modelling</span>
          <span class="bullet">Music Composition</span>
          <span class="bullet">Arcade Game Collector</span>
          <span class="bullet">Enthusiast Of All Things Retro</span>
          <span class="bullet">Nerd</span>
        </p>
        <div class="wordcloud">
          <!--
          begin tag cloud : generated by TagCrowd.com
          Feel free to modify as long as you keep this notice.

          EMBEDDING INSTRUCTIONS:
          1. Customize your cloud's style by editing the CSS where it says CUSTOMIZE below.
          2. Insert this code in its entirety into your webpage or blog post.

          This code and its rendered image are released under the Creative Commons Attribution-Noncommercial 3.0 Unported License. (http://creativecommons.org/licenses/by-nc/3.0/)

          For COMMERCIAL USE LICENSING, visit https://tagcrowd.com/licensing.html
          -->

          <div id="htmltagcloud"> <span id="0" class="wrd tagcloud4"><a href="#tagcloud">album</a></span> <span id="1" class="wrd tagcloud1"><a href="#tagcloud">amusement</a></span> <span id="2" class="wrd tagcloud9"><a href="#tagcloud">arcade</a></span> <span id="3" class="wrd tagcloud2"><a href="#tagcloud">around</a></span> <span id="4" class="wrd tagcloud3"><a href="#tagcloud">atari</a></span> <span id="5" class="wrd tagcloud0"><a href="#tagcloud">bally</a></span> <span id="6" class="wrd tagcloud0"><a href="#tagcloud">ca</a></span> <span id="7" class="wrd tagcloud1"><a href="#tagcloud">card</a></span> <span id="8" class="wrd tagcloud2"><a href="#tagcloud">centers</a></span> <span id="9" class="wrd tagcloud0"><a href="#tagcloud">chain</a></span> <span id="10" class="wrd tagcloud6"><a href="#tagcloud">circa</a></span> <span id="11" class="wrd tagcloud0"><a href="#tagcloud">city</a></span> <span id="12" class="wrd tagcloud0"><a href="#tagcloud">closed</a></span> <span id="13" class="wrd tagcloud1"><a href="#tagcloud">collection</a></span> <span id="14" class="wrd tagcloud0"><a href="#tagcloud">color</a></span> <span id="15" class="wrd tagcloud0"><a href="#tagcloud">company</a></span> <span id="16" class="wrd tagcloud1"><a href="#tagcloud">control</a></span> <span id="17" class="wrd tagcloud2"><a href="#tagcloud">cool</a></span> <span id="18" class="wrd tagcloud0"><a href="#tagcloud">couple</a></span> <span id="19" class="wrd tagcloud0"><a href="#tagcloud">coupon</a></span> <span id="20" class="wrd tagcloud0"><a href="#tagcloud">create</a></span> <span id="21" class="wrd tagcloud0"><a href="#tagcloud">days</a></span> <span id="22" class="wrd tagcloud0"><a href="#tagcloud">don</a></span> <span id="23" class="wrd tagcloud0"><a href="#tagcloud">download</a></span> <span id="24" class="wrd tagcloud2"><a href="#tagcloud">early</a></span> <span id="25" class="wrd tagcloud0"><a href="#tagcloud">end</a></span> <span id="26" class="wrd tagcloud0"><a href="#tagcloud">entertainment</a></span> <span id="27" class="wrd tagcloud0"><a href="#tagcloud">entire</a></span> <span id="28" class="wrd tagcloud4"><a href="#tagcloud">hirschberg</a></span> <span id="29" class="wrd tagcloud0"><a href="#tagcloud">exist</a></span> <span id="30" class="wrd tagcloud0"><a href="#tagcloud">favorite</a></span> <span id="31" class="wrd tagcloud0"><a href="#tagcloud">free</a></span> <span id="32" class="wrd tagcloud9"><a href="#tagcloud">games</a></span> <span id="33" class="wrd tagcloud0"><a href="#tagcloud">going</a></span> <span id="34" class="wrd tagcloud1"><a href="#tagcloud">helicopter</a></span> <span id="35" class="wrd tagcloud2"><a href="#tagcloud">hirschberg</a></span> <span id="36" class="wrd tagcloud1"><a href="#tagcloud">home</a></span> <span id="37" class="wrd tagcloud2"><a href="#tagcloud">included</a></span> <span id="38" class="wrd tagcloud0"><a href="#tagcloud">information</a></span> <span id="39" class="wrd tagcloud2"><a href="#tagcloud">kid</a></span> <span id="40" class="wrd tagcloud0"><a href="#tagcloud">listed</a></span> <span id="41" class="wrd tagcloud3"><a href="#tagcloud">location</a></span> <span id="42" class="wrd tagcloud0"><a href="#tagcloud">looks</a></span> <span id="43" class="wrd tagcloud2"><a href="#tagcloud">lot</a></span> <span id="44" class="wrd tagcloud2"><a href="#tagcloud">love</a></span> <span id="45" class="wrd tagcloud4"><a href="#tagcloud">machine</a></span> <span id="46" class="wrd tagcloud8"><a href="#tagcloud">mall</a></span> <span id="47" class="wrd tagcloud1"><a href="#tagcloud">manager</a></span> <span id="48" class="wrd tagcloud4"><a href="#tagcloud">memories</a></span> <span id="49" class="wrd tagcloud1"><a href="#tagcloud">model</a></span> <span id="50" class="wrd tagcloud0"><a href="#tagcloud">money</a></span> <span id="51" class="wrd tagcloud1"><a href="#tagcloud">movie</a></span> <span id="52" class="wrd tagcloud1"><a href="#tagcloud">name</a></span> <span id="53" class="wrd tagcloud1"><a href="#tagcloud">newsletters</a></span> <span id="54" class="wrd tagcloud2"><a href="#tagcloud">ny</a></span> <span id="55" class="wrd tagcloud1"><a href="#tagcloud">opened</a></span> <span id="56" class="wrd tagcloud1"><a href="#tagcloud">original</a></span> <span id="57" class="wrd tagcloud0"><a href="#tagcloud">owners</a></span> <span id="58" class="wrd tagcloud0"><a href="#tagcloud">paper</a></span> <span id="59" class="wrd tagcloud0"><a href="#tagcloud">people</a></span> <span id="60" class="wrd tagcloud3"><a href="#tagcloud">peter</a></span> <span id="61" class="wrd tagcloud4"><a href="#tagcloud">photos</a></span> <span id="62" class="wrd tagcloud4"><a href="#tagcloud">pictures</a></span> <span id="63" class="wrd tagcloud2"><a href="#tagcloud">pinball</a></span> <span id="64" class="wrd tagcloud4"><a href="#tagcloud">play</a></span> <span id="65" class="wrd tagcloud2"><a href="#tagcloud">please</a></span> <span id="66" class="wrd tagcloud0"><a href="#tagcloud">port</a></span> <span id="67" class="wrd tagcloud1"><a href="#tagcloud">quarters</a></span> <span id="68" class="wrd tagcloud4"><a href="#tagcloud">remember</a></span> <span id="69" class="wrd tagcloud1"><a href="#tagcloud">score</a></span> <span id="70" class="wrd tagcloud0"><a href="#tagcloud">sega</a></span> <span id="71" class="wrd tagcloud0"><a href="#tagcloud">several</a></span> <span id="72" class="wrd tagcloud2"><a href="#tagcloud">sign</a></span> <span id="73" class="wrd tagcloud4"><a href="#tagcloud">site</a></span> <span id="74" class="wrd tagcloud3"><a href="#tagcloud">space</a></span> <span id="75" class="wrd tagcloud0"><a href="#tagcloud">spaceport</a></span> <span id="76" class="wrd tagcloud0"><a href="#tagcloud">spent</a></span> <span id="77" class="wrd tagcloud4"><a href="#tagcloud">springfield</a></span> <span id="78" class="wrd tagcloud1"><a href="#tagcloud">started</a></span> <span id="79" class="wrd tagcloud0"><a href="#tagcloud">station</a></span> <span id="80" class="wrd tagcloud4"><a href="#tagcloud">store</a></span> <span id="81" class="wrd tagcloud3"><a href="#tagcloud">thanks</a></span> <span id="82" class="wrd tagcloud0"><a href="#tagcloud">think</a></span> <span id="83" class="wrd tagcloud1"><a href="#tagcloud">tico</a></span> <span id="84" class="wrd tagcloud10"><a href="#tagcloud">time-out</a></span> <span id="85" class="wrd tagcloud2"><a href="#tagcloud">tokens</a></span> <span id="86" class="wrd tagcloud0"><a href="#tagcloud">trip</a></span> <span id="87" class="wrd tagcloud4"><a href="#tagcloud">tunnel</a></span> <span id="88" class="wrd tagcloud6"><a href="#tagcloud">usa</a></span> <span id="89" class="wrd tagcloud4"><a href="#tagcloud">used</a></span> <span id="90" class="wrd tagcloud1"><a href="#tagcloud">va</a></span> <span id="91" class="wrd tagcloud1"><a href="#tagcloud">version</a></span> <span id="92" class="wrd tagcloud5"><a href="#tagcloud">video</a></span> <span id="93" class="wrd tagcloud3"><a href="#tagcloud">view</a></span> <span id="94" class="wrd tagcloud0"><a href="#tagcloud">virginia</a></span> <span id="95" class="wrd tagcloud0"><a href="#tagcloud">visit</a></span> <span id="96" class="wrd tagcloud0"><a href="#tagcloud">wars</a></span> <span id="97" class="wrd tagcloud0"><a href="#tagcloud">website</a></span> <span id="99" class="wrd tagcloud3"><a href="#tagcloud">years</a></span> </div><div id="credit">created at <a href="https://tagcrowd.com">TagCrowd.com</a></div>

          <!-- end tag cloud : generated by TagCrowd.com : please keep this notice -->
        </div>
      </center>
    </v-flex>
  </v-layout>
</template>

<script>

export default {
  name: 'HomeView',
  computed: {
    isMobile() {
      return this.$store.getters.isMobile
    }
  }
}
</script>

<style scoped lang="scss">
.HomeView {
  height: 100vh;
  margin: 20px 0 0 0;
  padding: 0;
  text-align: center;
  background-image: url('../assets/mylunarlander.jpg');
  background-position: top;
  background-repeat: no-repeat;
  background-size: 100% 100%;
  background-size: contain;
  h1 {
    font-size: 48px;
    font-weight: normal;
    text-shadow:
      0 0 5px #fff,
      0 0 10px #fff,
      0 0 20px #fff,
      0 0 40px #0ff,
      0 0 80px #0ff,
      0 0 90px #0ff,
      0 0 100px #0ff,
      0 0 150px #0ff;
  }
  p {
    max-width: 480px;
  }
  .the-layout {
    width: 100%;
    margin-top: 180px;
  }
  .bullet {
    font-weight: normal;
    margin-right: 20px;
    white-space: nowrap;
    display: inline-block;
    // color: rgb(204,127,127);
    // text-shadow:
    //   0 0 4px rgb(204,127,127),
    //   0 0 10px rgb(204,127,127);
    &:before {
      content: '• ';
    }
    font-family:
      "Segoe UI", 
      Roboto, 
      Oxygen-Sans, 
      Ubuntu, 
      Cantarell, 
      "Helvetica Neue", 
      sans-serif;    
  }
}

.wordcloud {
  opacity: 0;
  position: absolute;
  bottom: 0;
  pointer-events: none;
}

#htmltagcloud{
/******************************************
 * CUSTOMIZE CLOUD CSS BELOW (optional)
 */
	font-size: 50%;
	width: auto;		/* auto or fixed width, e.g. 500px   */
	font-family:'lucida grande','trebuchet ms',arial,helvetica,sans-serif;
	background-color:none;
	margin:1em 1em 0 1em;
	border: none;
	padding:2em; 
/******************************************
 * END CUSTOMIZE
 */
}
#htmltagcloud{line-height:2.4em;word-spacing:normal;letter-spacing:normal;text-transform:none;text-align:justify;text-indent:0}#htmltagcloud a:link{text-decoration:none}#htmltagcloud a:visited{text-decoration:none}#htmltagcloud a:hover{color:white;background-color:#05f}#htmltagcloud a:active{color:white;background-color:#03d}.wrd{padding:0;position:relative}.wrd a{text-decoration:none}.tagcloud0{font-size:1.0em;color:#ACC1F3;z-index:10}.tagcloud0 a{color:#ACC1F3}.tagcloud1{font-size:1.4em;color:#ACC1F3;z-index:9}.tagcloud1 a{color:#ACC1F3}.tagcloud2{font-size:1.8em;color:#86A0DC;z-index:8}.tagcloud2 a{color:#86A0DC}.tagcloud3{font-size:2.2em;color:#86A0DC;z-index:7}.tagcloud3 a{color:#86A0DC}.tagcloud4{font-size:2.6em;color:#607EC5;z-index:6}.tagcloud4 a{color:#607EC5}.tagcloud5{font-size:3.0em;color:#607EC5;z-index:5}.tagcloud5 a{color:#607EC5}.tagcloud6{font-size:3.3em;color:#4C6DB9;z-index:4}.tagcloud6 a{color:#4C6DB9}.tagcloud7{font-size:3.6em;color:#395CAE;z-index:3}.tagcloud7 a{color:#395CAE}.tagcloud8{font-size:3.9em;color:#264CA2;z-index:2}.tagcloud8 a{color:#264CA2}.tagcloud9{font-size:4.2em;color:#133B97;z-index:1}.tagcloud9 a{color:#133B97}.tagcloud10{font-size:4.5em;color:#002A8B;z-index:0}.tagcloud10 a{color:#002A8B}.freq{font-size:10pt !important;color:#bbb}#credit{text-align:center;color:#333;margin-bottom:0.6em;font:0.7em 'lucida grande',trebuchet,'trebuchet ms',verdana,arial,helvetica,sans-serif}#credit a:link{color:#777;text-decoration:none}#credit a:visited{color:#777;text-decoration:none}#credit a:hover{color:white;background-color:#05f}#credit a:active{text-decoration:underline}


</style>